options:
  stateGetter: plugins.builtin_stategetters.AutomaticToggleGetter
  updateFrequency: 1000
  port: 5000
states:
- deploying:
    text: Deploying, mfer'
    title: Deploy
    section: 'deploying'
    content: '<h1>My title here</h1>Some html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome Some html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome Some html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome Some html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome html hereSome html here <br> :-D <br> More here'
- deploying_completing:
    section: 'deploying'
- deploying_complete:
    section: 'deploying'
- testing
- testing_complete
- idle